var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/papers/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__14ym91u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0bw_x_7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_043e-qe.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zkgeet._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ujudfi._.js")
R.c("server/chunks/ssr/app_loading_tsx_0a1flg9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_papers_page_actions_0aiprtz.js")
R.m(36464)
module.exports=R.m(36464).exports
