// Generates scripts/seed.sql from the JSON files in content/, ready to load
// into D1. The content/*.json files remain in the repo purely as this seed
// source — the running app reads from D1, not from them.
//
//   node scripts/seed.mjs
//   wrangler d1 execute zunera-content --local  --file=scripts/seed.sql
//   wrangler d1 execute zunera-content --remote --file=scripts/seed.sql
//
// (the npm scripts db:seed:local / db:seed do both steps.)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// Singleton sections store one object; collections store an ordered array.
const SINGLETONS = ["site", "pages", "seo"];
const COLLECTIONS = [
  "nav",
  "custom-pages",
  "affiliations",
  "papers",
  "opinions",
  "interviews",
  "categories",
  "posts",
];

const sqlEscape = (s) => s.replace(/'/g, "''");
const read = (name) =>
  JSON.parse(readFileSync(path.join(root, "content", `${name}.json`), "utf8"));
const insert = (section, position, data) =>
  `INSERT INTO content_items (section, position, data) VALUES ('${section}', ${position}, '${sqlEscape(
    JSON.stringify(data)
  )}');`;

const out = ["-- Generated by scripts/seed.mjs — do not edit by hand.", "DELETE FROM content_items;"];

for (const section of SINGLETONS) {
  out.push(insert(section, 0, read(section)));
}
for (const section of COLLECTIONS) {
  const items = read(section);
  items.forEach((item, i) => out.push(insert(section, i, item)));
}

const target = path.join(root, "scripts", "seed.sql");
writeFileSync(target, out.join("\n") + "\n");
console.log(`Wrote ${path.relative(root, target)} (${out.length - 2} rows).`);
